### ISSUE TITLE
[Question] vfox config -l not all configurations shown

### ISSUE THREAD

**Issue by jan-bar** [version-fox/vfox#233]
Currently viewing all configurations
```shell
vfox config -l

proxy.url = http://proxy.com:1080
proxy.enable = true
storage.sdkPath = D:\install
legacyVersionFile.enable = false
```

The configuration file content is as follows
```yaml
proxy:
    url: http://proxy.com:1080
    enable: true
storage:
    sdkPath: D:\install
registry:
    address: ""
legacyVersionFile:
    enable: false
```

Here is the code that ignores the configuration: https://github.com/version-fox/vfox/blob/main/cmd/commands/config.go#L71-L74

Why should we ignore this type of configuration?   `registry.address = ""`

If you don’t read the documentation and just execute the command, the user may not know this configuration.
