### ISSUE TITLE
[Feature]: support new format file `.vfox.toml`

### ISSUE THREAD

**Issue by aooohan** [version-fox/vfox#467]
#### 1. Your usage scenarios?

`.tool-versions` file has limited expressive capabilities. In `v1.0.0`, we will use a new file format `.vfox.toml` as the primary format, while still compatible with  `.tool-versions`.

#### 2. What is your expected outcome?

The new format is as follows:

```toml
[tools]
nodejs = '21.5.1'
java = {version = '1.1.1' , flag=true}

```
